-- ============================================================
-- OmniPlay - Corrected Database Setup Blueprint for Supabase
-- Run this SQL in your Supabase SQL Editor (Dashboard > SQL Editor)
-- This creates all 13 tables matching the Next.js production schema.
-- ============================================================

-- 1. Site Configuration
CREATE TABLE IF NOT EXISTS public.zon_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_name text NOT NULL DEFAULT 'OmniPlay',
  profile_tagline text NOT NULL DEFAULT 'Welcome to OmniPlay',
  site_logo_sm text NOT NULL DEFAULT '',
  site_logo_light text NOT NULL DEFAULT '',
  site_logo_dark text NOT NULL DEFAULT '',
  site_favicon text NOT NULL DEFAULT '',
  head_code text NOT NULL DEFAULT '',
  footer_content text NOT NULL DEFAULT 'OmniPlay brings you a wide selection of free online games designed for quick, smooth, and enjoyable play. Whether you want to play alone, challenge your friends, or explore something new, OmniPlay gives you instant access without downloads, sign-ups, popups, or distractions.',
  site_title text NOT NULL DEFAULT 'OmniPlay - Play Free HTML5 Games',
  site_desc text NOT NULL DEFAULT 'Play the best free online HTML5 games instantly in your browser.',
  site_keywords text NOT NULL DEFAULT 'online games, html5 games, free games',
  sidebar_show integer NOT NULL DEFAULT 1,
  category_slider_show integer NOT NULL DEFAULT 1,
  featured_game_slider integer NOT NULL DEFAULT 1,
  popular_views integer NOT NULL DEFAULT 10,
  site_color text NOT NULL DEFAULT '#1583f9',
  section_games_limit integer NOT NULL DEFAULT 10,
  games_title text NOT NULL DEFAULT '',
  games_desc text NOT NULL DEFAULT '',
  play_title text NOT NULL DEFAULT '',
  play_desc text NOT NULL DEFAULT '',
  profile_title text NOT NULL DEFAULT '',
  profile_desc text NOT NULL DEFAULT '',
  category_title text NOT NULL DEFAULT '',
  category_desc text NOT NULL DEFAULT '',
  animate_class text NOT NULL DEFAULT 'fadeInDown',
  cursor_color text NOT NULL DEFAULT '#fff',
  custom_cursor integer NOT NULL DEFAULT 0,
  theme text NOT NULL DEFAULT 'poko',
  blog integer NOT NULL DEFAULT 0,
  gamepix_sid text NOT NULL DEFAULT '10605',
  auto_fetch integer NOT NULL DEFAULT 0,
  auto_fetch_amount integer NOT NULL DEFAULT 90,
  auto_fetch_timing integer NOT NULL DEFAULT 1,
  auto_fetch_pub text NOT NULL DEFAULT 'gamepix',
  auto_fetch_page integer NOT NULL DEFAULT 0,
  auto_fetch_all_games_fetched integer NOT NULL DEFAULT 0,
  auto_fetch_game_publisher text NOT NULL DEFAULT '',
  spotlight_game_id integer DEFAULT NULL
);

ALTER TABLE public.zon_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_config_select" ON public.zon_config FOR SELECT USING (true);
CREATE POLICY "zon_config_insert" ON public.zon_config FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_config_update" ON public.zon_config FOR UPDATE USING (true);
CREATE POLICY "zon_config_delete" ON public.zon_config FOR DELETE USING (true);

-- Seed Default Config
INSERT INTO public.zon_config (
  id, site_name, profile_tagline, site_logo_sm, site_logo_light, site_logo_dark, site_favicon,
  head_code, footer_content, site_title, site_desc, site_keywords, sidebar_show,
  category_slider_show, featured_game_slider, popular_views, site_color, section_games_limit,
  games_title, games_desc, play_title, play_desc, profile_title, profile_desc,
  category_title, category_desc, animate_class, cursor_color, custom_cursor, theme, blog,
  gamepix_sid, auto_fetch, auto_fetch_amount, auto_fetch_timing, auto_fetch_pub,
  auto_fetch_page, auto_fetch_all_games_fetched, auto_fetch_game_publisher
) VALUES (
  1, 'OmniPlay', 'Welcome to OmniPlay', '', '', '', '',
  '', 'OmniPlay brings you a wide selection of free online games designed for quick, smooth, and enjoyable play. Whether you want to play alone, challenge your friends, or explore something new, OmniPlay gives you instant access without downloads, sign-ups, popups, or distractions. You can play anytime on desktop, tablet, or mobile, making it easy to enjoy your favorite games at home or on the go.',
  'OmniPlay - Play Free HTML5 Games', 'Play the best free online HTML5 games instantly in your browser.', 'online games, html5 games, free games',
  1, 1, 1, 10, '#1583f9', 10, '', '', '', '', '', '', '', '', 'fadeInDown', '#fff', 0, 'poko', 0,
  '10605', 0, 90, 1, 'gamepix', 0, 0, ''
) ON CONFLICT (id) DO NOTHING;

-- 2. Users
CREATE TABLE IF NOT EXISTS public.zon_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(2000) NOT NULL DEFAULT '',
  email varchar(2000) NOT NULL DEFAULT '',
  username varchar(3000) NOT NULL DEFAULT '',
  password text NOT NULL DEFAULT '',
  user_pic text NOT NULL DEFAULT 'user-pic.png',
  status integer NOT NULL DEFAULT 1,
  is_admin integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_users_select" ON public.zon_users FOR SELECT USING (true);
CREATE POLICY "zon_users_insert" ON public.zon_users FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_users_update" ON public.zon_users FOR UPDATE USING (true);
CREATE POLICY "zon_users_delete" ON public.zon_users FOR DELETE USING (true);

-- 3. Game Categories
CREATE TABLE IF NOT EXISTS public.zon_category (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL DEFAULT '',
  slug text NOT NULL DEFAULT ''
);

ALTER TABLE public.zon_category ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_category_select" ON public.zon_category FOR SELECT USING (true);
CREATE POLICY "zon_category_insert" ON public.zon_category FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_category_update" ON public.zon_category FOR UPDATE USING (true);
CREATE POLICY "zon_category_delete" ON public.zon_category FOR DELETE USING (true);

-- Seed Default Categories
INSERT INTO public.zon_category (id, name, slug) VALUES
  (1, 'Adventure', 'adventure'),
  (2, 'Shooting', 'shooting'),
  (3, '3D', '3d'),
  (4, 'Sports', 'sports'),
  (5, 'Arcade', 'arcade'),
  (6, 'Hypercasual', 'hypercasual'),
  (7, 'Puzzles', 'puzzles'),
  (8, 'Clicker', 'clicker'),
  (9, 'Girls', 'girls'),
  (10, 'Action', 'action'),
  (12, 'Racing', 'racing'),
  (13, 'Fighting', 'fighting'),
  (14, 'Boys', 'boys'),
  (15, 'Multiplayer', 'multiplayer'),
  (16, 'Soccer', 'soccer')
ON CONFLICT (id) DO NOTHING;

-- 4. Games
CREATE TABLE IF NOT EXISTS public.zon_games (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name text NOT NULL DEFAULT '',
  game_description text NOT NULL DEFAULT '',
  game_image_url text NOT NULL DEFAULT '',
  game_url text NOT NULL DEFAULT '',
  game_published text NOT NULL DEFAULT '',
  game_category text NOT NULL DEFAULT '',
  game_status integer NOT NULL DEFAULT 1,
  game_played integer NOT NULL DEFAULT 0,
  game_banner_url text DEFAULT '',
  is_featured integer NOT NULL DEFAULT 0,
  game_card_size text NOT NULL DEFAULT 'normal'
);

ALTER TABLE public.zon_games ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_games_select" ON public.zon_games FOR SELECT USING (true);
CREATE POLICY "zon_games_insert" ON public.zon_games FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_games_update" ON public.zon_games FOR UPDATE USING (true);
CREATE POLICY "zon_games_delete" ON public.zon_games FOR DELETE USING (true);

-- 5. Game Likes
CREATE TABLE IF NOT EXISTS public.zon_likes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_ip text NOT NULL DEFAULT '',
  game_id integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_likes_select" ON public.zon_likes FOR SELECT USING (true);
CREATE POLICY "zon_likes_insert" ON public.zon_likes FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_likes_delete" ON public.zon_likes FOR DELETE USING (true);

-- 6. Game Unlikes / Dislikes
CREATE TABLE IF NOT EXISTS public.zon_unlikes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_ip text NOT NULL DEFAULT '',
  game_id integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_unlikes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_unlikes_select" ON public.zon_unlikes FOR SELECT USING (true);
CREATE POLICY "zon_unlikes_insert" ON public.zon_unlikes FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_unlikes_delete" ON public.zon_unlikes FOR DELETE USING (true);

-- 7. Comments
CREATE TABLE IF NOT EXISTS public.zon_comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL DEFAULT 0,
  game_id integer NOT NULL DEFAULT 0,
  subject varchar(2000) NOT NULL DEFAULT '',
  date varchar(2000) NOT NULL DEFAULT ''
);

ALTER TABLE public.zon_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_comments_select" ON public.zon_comments FOR SELECT USING (true);
CREATE POLICY "zon_comments_insert" ON public.zon_comments FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_comments_update" ON public.zon_comments FOR UPDATE USING (true);
CREATE POLICY "zon_comments_delete" ON public.zon_comments FOR DELETE USING (true);

-- 8. Reports
CREATE TABLE IF NOT EXISTS public.zon_report (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name text NOT NULL DEFAULT '',
  report_subject text NOT NULL DEFAULT '',
  game_id integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_report ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_report_select" ON public.zon_report FOR SELECT USING (true);
CREATE POLICY "zon_report_insert" ON public.zon_report FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_report_delete" ON public.zon_report FOR DELETE USING (true);

-- 9. Static Pages
CREATE TABLE IF NOT EXISTS public.zon_pages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL DEFAULT '',
  "desc" text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT ''
);

ALTER TABLE public.zon_pages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_pages_select" ON public.zon_pages FOR SELECT USING (true);
CREATE POLICY "zon_pages_insert" ON public.zon_pages FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_pages_update" ON public.zon_pages FOR UPDATE USING (true);
CREATE POLICY "zon_pages_delete" ON public.zon_pages FOR DELETE USING (true);

-- 10. Blog
CREATE TABLE IF NOT EXISTS public.zon_blog (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blog_title text NOT NULL DEFAULT '',
  blog_desc text NOT NULL DEFAULT '',
  blog_content text NOT NULL DEFAULT '',
  blog_image text NOT NULL DEFAULT '',
  blog_date text NOT NULL DEFAULT ''
);

ALTER TABLE public.zon_blog ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_blog_select" ON public.zon_blog FOR SELECT USING (true);
CREATE POLICY "zon_blog_insert" ON public.zon_blog FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_blog_update" ON public.zon_blog FOR UPDATE USING (true);
CREATE POLICY "zon_blog_delete" ON public.zon_blog FOR DELETE USING (true);

-- 11. Advertisements
CREATE TABLE IF NOT EXISTS public.zon_ads (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL DEFAULT '',
  ad_name text NOT NULL DEFAULT '',
  status integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_ads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_ads_select" ON public.zon_ads FOR SELECT USING (true);
CREATE POLICY "zon_ads_insert" ON public.zon_ads FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_ads_update" ON public.zon_ads FOR UPDATE USING (true);
CREATE POLICY "zon_ads_delete" ON public.zon_ads FOR DELETE USING (true);

-- Seed Default Ads
INSERT INTO public.zon_ads (id, ad_name, code, status) VALUES
  (1, '728x90', '<div class="w-full h-20 bg-slate-800/40 border border-white/5 rounded-xl flex items-center justify-center text-slate-500 font-bold text-sm">Responsive Banner Ad Slot</div>', 1),
  (2, '300x250', '<div class="w-full h-[250px] bg-slate-800/40 border border-white/5 rounded-xl flex items-center justify-center text-slate-500 font-bold text-sm">Sidebar Square Ad Slot</div>', 1)
ON CONFLICT (id) DO NOTHING;

-- 12. Featured Games
CREATE TABLE IF NOT EXISTS public.zon_featured_games (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_featured_games ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_featured_select" ON public.zon_featured_games FOR SELECT USING (true);
CREATE POLICY "zon_featured_insert" ON public.zon_featured_games FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_featured_update" ON public.zon_featured_games FOR UPDATE USING (true);
CREATE POLICY "zon_featured_delete" ON public.zon_featured_games FOR DELETE USING (true);

-- 13. Sections
CREATE TABLE IF NOT EXISTS public.zon_section (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_name text NOT NULL DEFAULT '',
  section_category text NOT NULL DEFAULT ''
);

ALTER TABLE public.zon_section ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_section_select" ON public.zon_section FOR SELECT USING (true);
CREATE POLICY "zon_section_insert" ON public.zon_section FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_section_update" ON public.zon_section FOR UPDATE USING (true);
CREATE POLICY "zon_section_delete" ON public.zon_section FOR DELETE USING (true);

-- ============================================================
-- Setup complete! Now go to /install to create your admin account.
-- ============================================================
