-- ============================================================
-- OmniPlay - Complete Database Setup for Supabase
-- Run this SQL in your Supabase SQL Editor (Dashboard > SQL Editor)
-- This creates all required tables with RLS policies.
-- ============================================================

-- 1. Site Configuration
CREATE TABLE IF NOT EXISTS public.zon_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_name text NOT NULL DEFAULT 'OmniPlay',
  site_title text NOT NULL DEFAULT 'OmniPlay - Play Free HTML5 Games',
  profile_tagline text NOT NULL DEFAULT 'Let the world play',
  site_desc text NOT NULL DEFAULT 'Play the best free online HTML5 games instantly in your browser.',
  site_keywords text NOT NULL DEFAULT 'online games, html5 games, free games',
  site_color text NOT NULL DEFAULT '#1583f9',
  logo text NOT NULL DEFAULT '',
  logo_dark text NOT NULL DEFAULT '',
  logo_mobile text NOT NULL DEFAULT '',
  favicon text NOT NULL DEFAULT '',
  footer_text text NOT NULL DEFAULT '',
  analytics_code text NOT NULL DEFAULT '',
  custom_head text NOT NULL DEFAULT '',
  custom_css text NOT NULL DEFAULT ''
);

ALTER TABLE public.zon_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_config_select" ON public.zon_config FOR SELECT USING (true);
CREATE POLICY "zon_config_insert" ON public.zon_config FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_config_update" ON public.zon_config FOR UPDATE USING (true);
CREATE POLICY "zon_config_delete" ON public.zon_config FOR DELETE USING (true);

-- 2. Users
CREATE TABLE IF NOT EXISTS public.zon_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(2000) NOT NULL DEFAULT '',
  email varchar(2000) NOT NULL DEFAULT '',
  username varchar(3000) NOT NULL DEFAULT '',
  password text NOT NULL DEFAULT '',
  user_pic text NOT NULL DEFAULT 'user-pic.png',
  status integer NOT NULL DEFAULT 1,
  is_admin integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_users_select" ON public.zon_users FOR SELECT USING (true);
CREATE POLICY "zon_users_insert" ON public.zon_users FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_users_update" ON public.zon_users FOR UPDATE USING (true);
CREATE POLICY "zon_users_delete" ON public.zon_users FOR DELETE USING (true);

-- 3. Game Categories
CREATE TABLE IF NOT EXISTS public.zon_category (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cat_name text NOT NULL DEFAULT '',
  cat_icon text NOT NULL DEFAULT '',
  cat_count integer NOT NULL DEFAULT 0,
  cat_order integer NOT NULL DEFAULT 0,
  cat_status integer NOT NULL DEFAULT 1,
  cat_color text NOT NULL DEFAULT '#1583f9'
);

ALTER TABLE public.zon_category ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_category_select" ON public.zon_category FOR SELECT USING (true);
CREATE POLICY "zon_category_insert" ON public.zon_category FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_category_update" ON public.zon_category FOR UPDATE USING (true);
CREATE POLICY "zon_category_delete" ON public.zon_category FOR DELETE USING (true);

-- 4. Games
CREATE TABLE IF NOT EXISTS public.zon_games (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL DEFAULT '',
  "desc" text NOT NULL DEFAULT '',
  thumb text NOT NULL DEFAULT '',
  url text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT '0',
  category text NOT NULL DEFAULT '',
  plays integer NOT NULL DEFAULT 0,
  likes integer NOT NULL DEFAULT 0,
  tags text NOT NULL DEFAULT '',
  is_featured integer NOT NULL DEFAULT 0,
  banner_url text NOT NULL DEFAULT '',
  spotlight integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_games ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_games_select" ON public.zon_games FOR SELECT USING (true);
CREATE POLICY "zon_games_insert" ON public.zon_games FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_games_update" ON public.zon_games FOR UPDATE USING (true);
CREATE POLICY "zon_games_delete" ON public.zon_games FOR DELETE USING (true);

-- 5. Game Likes
CREATE TABLE IF NOT EXISTS public.zon_likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_ip text NOT NULL DEFAULT '',
  game_id integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_likes_select" ON public.zon_likes FOR SELECT USING (true);
CREATE POLICY "zon_likes_insert" ON public.zon_likes FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_likes_delete" ON public.zon_likes FOR DELETE USING (true);

-- 6. Game Unlikes / Dislikes
CREATE TABLE IF NOT EXISTS public.zon_unlikes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_ip text NOT NULL DEFAULT '',
  game_id integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_unlikes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_unlikes_select" ON public.zon_unlikes FOR SELECT USING (true);
CREATE POLICY "zon_unlikes_insert" ON public.zon_unlikes FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_unlikes_delete" ON public.zon_unlikes FOR DELETE USING (true);

-- 7. Comments
CREATE TABLE IF NOT EXISTS public.zon_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id integer NOT NULL DEFAULT 0,
  user_name text NOT NULL DEFAULT '',
  user_email text NOT NULL DEFAULT '',
  comment text NOT NULL DEFAULT '',
  status integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.zon_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_comments_select" ON public.zon_comments FOR SELECT USING (true);
CREATE POLICY "zon_comments_insert" ON public.zon_comments FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_comments_update" ON public.zon_comments FOR UPDATE USING (true);
CREATE POLICY "zon_comments_delete" ON public.zon_comments FOR DELETE USING (true);

-- 8. Reports
CREATE TABLE IF NOT EXISTS public.zon_report (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name text NOT NULL DEFAULT '',
  report_subject text NOT NULL DEFAULT '',
  game_id integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_report ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_report_select" ON public.zon_report FOR SELECT USING (true);
CREATE POLICY "zon_report_insert" ON public.zon_report FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_report_delete" ON public.zon_report FOR DELETE USING (true);

-- 9. Static Pages
CREATE TABLE IF NOT EXISTS public.zon_pages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL DEFAULT '',
  "desc" text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT ''
);

ALTER TABLE public.zon_pages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_pages_select" ON public.zon_pages FOR SELECT USING (true);
CREATE POLICY "zon_pages_insert" ON public.zon_pages FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_pages_update" ON public.zon_pages FOR UPDATE USING (true);
CREATE POLICY "zon_pages_delete" ON public.zon_pages FOR DELETE USING (true);

-- 10. Blog
CREATE TABLE IF NOT EXISTS public.zon_blog (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL DEFAULT '',
  slug text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  thumb text NOT NULL DEFAULT '',
  author text NOT NULL DEFAULT '',
  status integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.zon_blog ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_blog_select" ON public.zon_blog FOR SELECT USING (true);
CREATE POLICY "zon_blog_insert" ON public.zon_blog FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_blog_update" ON public.zon_blog FOR UPDATE USING (true);
CREATE POLICY "zon_blog_delete" ON public.zon_blog FOR DELETE USING (true);

-- 11. Advertisements
CREATE TABLE IF NOT EXISTS public.zon_ads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad_name text NOT NULL DEFAULT '',
  ad_code text NOT NULL DEFAULT '',
  ad_status integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_ads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_ads_select" ON public.zon_ads FOR SELECT USING (true);
CREATE POLICY "zon_ads_insert" ON public.zon_ads FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_ads_update" ON public.zon_ads FOR UPDATE USING (true);
CREATE POLICY "zon_ads_delete" ON public.zon_ads FOR DELETE USING (true);

-- 12. Featured Games
CREATE TABLE IF NOT EXISTS public.zon_featured_games (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id integer NOT NULL DEFAULT 0,
  featured_order integer NOT NULL DEFAULT 0
);

ALTER TABLE public.zon_featured_games ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_featured_select" ON public.zon_featured_games FOR SELECT USING (true);
CREATE POLICY "zon_featured_insert" ON public.zon_featured_games FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_featured_update" ON public.zon_featured_games FOR UPDATE USING (true);
CREATE POLICY "zon_featured_delete" ON public.zon_featured_games FOR DELETE USING (true);

-- 13. Sections (homepage sections)
CREATE TABLE IF NOT EXISTS public.zon_section (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_name text NOT NULL DEFAULT '',
  section_category text NOT NULL DEFAULT ''
);

ALTER TABLE public.zon_section ENABLE ROW LEVEL SECURITY;
CREATE POLICY "zon_section_select" ON public.zon_section FOR SELECT USING (true);
CREATE POLICY "zon_section_insert" ON public.zon_section FOR INSERT WITH CHECK (true);
CREATE POLICY "zon_section_update" ON public.zon_section FOR UPDATE USING (true);
CREATE POLICY "zon_section_delete" ON public.zon_section FOR DELETE USING (true);

-- ============================================================
-- Setup complete! Now go to /install to create your admin account.
-- ============================================================
